import * as React from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import TopComponent from "components/TopComponent";
//import { Box, Button, Typography, Modal } from "@mui/material";
import { ClientRequest } from "http";
import Link from "next/link";

// =================================
import { motion } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

// const style = {
//   position: "absolute" as "absolute",
//   top: "50%",
//   left: "50%",
//   transform: "translate(-50%, -50%)",
//   width: 400,
//   height: 400,
//   bgcolor: "background.paper",
//   border: "2px solid #000",
//   boxShadow: 24,
//   p: 4,
// };

export default function Home() {
  // const [open, setOpen] = React.useState(false);
  // const handleOpen = () => setOpen(true);
  // const handleClose = () => setOpen(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TopComponent />

        {/* ============================================== */}

        {/* <Button onClick={handleOpen}>
          <motion.li
            className="item"
            whileHover={{
              position: "relative",
              zIndex: 1,
              background: "white",
              scale: 1.2,
              transition: {
                duration: 0.2,
              },
            }}
          >
            <img
              src="https://toplogos.ru/images/thumbs/preview-logo-mts.png"
              alt="Логотип MTS"
            />
          </motion.li>
        </Button>
        <Modal
          open={open}
          onClose={handleClose}
          aria-labelledby="modal-modal-title"
          aria-describedby="modal-modal-description"
        >
          <Box sx={style}>
            <Typography id="modal-modal-title" variant="h6" component="h2">
              Text in a modal
            </Typography>
            <Typography id="modal-modal-description" sx={{ mt: 2 }}>
              Duis mollis, est non commodo luctus, nisi erat porttitor ligula.
            </Typography>
          </Box>
        </Modal> */}

        <Link legacyBehavior href={"/payment"}>Payment</Link>

      </main>
    </>
  );
}
